### ISSUE TITLE
main does not build: .gitignore swallowed internal/specs/coverage.go

### ISSUE THREAD

**Issue by petar-djukic** [petar-djukic/md-to-tex#41]
Introduced by #25 (PR #40). `main` does not compile:

```
internal/specs/specs.go:53:11: undefined: Coverage
internal/specs/specs.go:173:32: undefined: checkCoverage
```

## Cause

`.gitignore` line 16 is `coverage.*`, meant for Go coverage output such as `coverage.out` and `coverage.html`. It is unanchored, so it matches at any depth and excluded `internal/specs/coverage.go`. `git add -A` skipped the file silently. Its test, `internal/specs/coverage_test.go`, does not match the pattern — an underscore is not a dot — so the test went in and now references code that is not there.

The work was verified inside the worktree, where the file existed on disk, so every check passed while the commit was already incomplete. Nothing in the flow reads the committed tree rather than the working one.

## Fix

- Anchor the rule to the repository root, `/coverage.*`, so it keeps guarding coverage output without claiming every file whose name begins with coverage. Same for any other unanchored artifact pattern that could match a source file.
- Restore `internal/specs/coverage.go`.

## Acceptance criteria

- `main` builds, and `mage audit` and `go test ./...` are green from a fresh clone rather than from a worktree.
- `git check-ignore -v internal/specs/coverage.go` reports nothing.
- The ignore rules are checked against the tracked source files, so a pattern that would swallow one is visible.

Estimated LOC: ~10 production restored, plus a check.

**Comment by petar-djukic** [comment]
Completed in commit 5af8396. `main` builds again, verified from a fresh clone rather than from the worktree.

`.gitignore` carried `coverage.*` unanchored. Unanchored patterns match at any depth, so it claimed `internal/specs/coverage.go`, and `git add -A` skipped it silently. Its test does not match the pattern — an underscore is not a dot — so `coverage_test.go` landed and referenced code that was not in the tree. Every check I ran passed, because every check ran in the working tree where the file existed.

The artifact patterns are now anchored to the repository root: `/coverage.*`, `/*.out`, `/*.coverprofile`, `/profile.cov`. They still guard what they were written for, and no longer claim a source file whose name happens to begin the same way.

`internal/specs/coverage.go` is restored. It was never committed and the worktree was gone, so it is rewritten rather than recovered; `coverage_test.go` was in the tree and pins the API exactly, so the reconstruction is checked by its own tests rather than by my memory of it.

`TestNoSourceFileIsIgnored` is the guard. It walks the tree and passes every Go, YAML, markdown, and tex file through `git check-ignore`, failing with the paths a commit would drop. I checked it fails for the right reason: against the old rule it fails naming `internal/specs/coverage.go`, and against the anchored rule it passes.

The lesson worth keeping is not about this pattern. Verifying in the working tree cannot see what the commit left out, and a fresh clone of the pushed branch can. That is now how I check the end of a unit.

Verification: from a clean clone of this branch, `go build ./...`, `go test ./...`, and `mage audit` are all green — 184 of 184 requirements covered, gated.

Actual LOC: 183 production restored, 63 test (Estimated: ~10 production restored, plus a check)
